persistence:
  volumeName: local-volume
  
  volumeClaimName: mysql-pvc
  
  reclaimPolicy: Delete
  
  capacity: 1Gi
  
  hostPath:
    path: /tmp/my-pv
    type: DirectoryOrCreate

controller:
  name: mysql
  
  serviceName: mysql
  
  replicaCount: 1
  
  serviceAccountName: db-secret-sa
  
  containerName: mysql
  
  containerImage: mysql
  
  containerPort: 3306
